project:
  type: website

website:
  title: "Data Science Portfolio"
  favicon: Edward Quinn-min.jpg
  navbar:
    left: 
      - text: Python
        href: Python.qmd
      - text: R
        href: R.qmd
      - text: Resume
        href: resume.qmd
format:
  html:
    theme: minty
    code-link: true
    code-fold: show
    highlight-style: breeze
    
editor: source


